line-length = 88
target-version = "py310"

[lint]
select = ["E", "F", "B"]
ignore = ["E203", "E501"]

[lint.per-file-ignores]
"__init__.py" = ["F401"]  # Imported but unused in __init__ files
"tests/**/*.py" = ["F401", "E402", "F821", "E712", "E501"]  # Various issues in test files
"tests/archive/**/*.py" = ["F401", "E402", "F821", "E712", "E731", "E501", "W191", "E101", "W293"]  # Additional issues in archived test files
"src/mcp_agile_flow/register_memory_tools.py" = ["F821", "E501"]  # Undefined names in memory tools 