[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mcp-agile-flow"
version = "0.1.0"
authors = [
    {name = "Sho Mian", email = "your.email@example.com"},
]
description = "MCP server implementations for enhancing agile workflows in Cursor"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "mcp>=1.4.1",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.25.3",
    "aiohttp>=3.11.14",
]

[project.optional-dependencies]
test = [
    "agno>=1.1.14",
    "mcp>=1.4.1",
    "rich>=13.9.4",
    "openai>=1.67.0"
]

[project.urls]
Homepage = "https://github.com/yourusername/mcp-agile-flow"
Issues = "https://github.com/yourusername/mcp-agile-flow/issues"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
python_classes = "Test*"
addopts = "--verbose"
norecursedirs = ["tests/archive"]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"

[tool.black]
line-length = 88
target-version = ["py310"]
include = '\.pyi?$'

[tool.ruff]
line-length = 88
target-version = "py310"
select = ["E", "F", "B", "I"]
ignore = []

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
